#!/usr/bin/env python3
"""Step 7 — build paper/preprint.md from paper/preprint_template.md and paper/stats.json.

Every {{key}} (dotted for nested values, e.g. {{recovery.B_rmse_P}}) is replaced by the value
in stats.json. A key that does not exist stops the build, so the text can never quote a
number the pipeline did not produce.

    python code/07_build_paper.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def lookup(stats, key):
    v = stats
    for part in key.split("."):
        if not isinstance(v, dict) or part not in v:
            raise KeyError(key)
        v = v[part]
    return v


def main():
    stats = json.load(open(os.path.join(ROOT, "paper", "stats.json")))
    tpl = open(os.path.join(ROOT, "paper", "preprint_template.md")).read()
    missing = []

    def sub(m):
        try:
            return str(lookup(stats, m.group(1).strip()))
        except KeyError:
            missing.append(m.group(1))
            return m.group(0)

    out = re.sub(r"\{\{([^}]+)\}\}", sub, tpl)
    if missing:
        sys.exit(f"keys not in stats.json: {sorted(set(missing))}")
    out = out.replace("<!-- Built by code/07_build_paper.py. Edit THIS template, never preprint.md.",
                      "<!-- GENERATED by code/07_build_paper.py from preprint_template.md — do not edit.")
    open(os.path.join(ROOT, "paper", "preprint.md"), "w").write(out)
    print("wrote paper/preprint.md")


if __name__ == "__main__":
    main()
